import "unknwn.idl";
import "DataContract.idl";

[object, uuid(73B047A0-40A4-4D23-A5D3-5F7A87156E12)]
interface IDriverService : IUnknown
{
 HRESULT SetTrackerState([in] struct dTrackerBase tracker);
 HRESULT UpdateTracker([in] struct dTrackerBase tracker);

 HRESULT RequestVrRestart([in, string] wchar_t* message);
 HRESULT PingDriverService([out] __int64* ms);

 HRESULT SetDriverPose([in] unsigned int id, [in] struct dDriverPose pose);
 HRESULT EnableOverride([in] unsigned int id, [in] boolean isEnabled);

 HRESULT UpdateInputBoolean([in] enum dTrackerType tracker, [in, string] wchar_t* path, [in] boolean value);
 HRESULT UpdateInputScalar([in] enum dTrackerType tracker, [in, string] wchar_t* path, [in] float value);
};
